<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" type="image/png" href="{{ asset('storage') }}/{{ $company?->logo }}" />
    <title>{{$company?->name ?? ""}}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link rel="stylesheet" href="{{ URL::to('css/bootstrap.mins.css')}}">

    <style type="text/css">
        * {
            font-size: 14px;
            line-height: 24px;
            font-family: 'Ubuntu', sans-serif;
            text-transform: capitalize;
        }
        .btn {
            padding: 7px 10px;
            text-decoration: none;
            border: none;
            display: block;
            text-align: center;
            margin: 7px;
            cursor:pointer;
        }

        .btn-info {
            background-color: #999;
            color: #FFF;
        }

        .btn-primary {
            background-color: #6449e7;
            color: #FFF;
            width: 100%;
        }
    
        small{font-size:11px;}
    </style>
  </head>
<body>


<div class="card col-md-8 col-md-offset-2">
	<div class="card-body">
		<div class="p-0 card-body table-responsive">
            <h2 style="margin-bottom: 20px;">REPORT GENERATED FROM {{ $fromdate }} TO {{ $todate }}</h2>
			<table class="table table-table table-bordered">
				<thead>
                    <tr class="bg-info">
						<th>#</th>
						<th>Order Ref</th>
                        <th>Order Status</th>
                        <th>Customer</th>
                        <th>Subtotal</th>
                        <th>Paid</th>
                        <th>Left</th>
					</tr>
				</thead>
				<tbody>
                        @php
                            $total = 0;
                            $paid = 0;
                            $owe = 0;
                        @endphp
                        @foreach ($data as $item)
                        @php
                            $total += $item->grand_total;
                            $paid += $item->paid_amountuantity;
                        @endphp
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $item->order_reff }}</td>
                                <td>{{ $item->status }}</td>
                                <td>{{ $item->client->customer_name ?? "" }}</td>
    
                                <td style="font-size: 12px;text-align: left">{{ number_format($item->total ?? 0, 2) }}</td>
    
                                <td style="font-size: 12px;text-align: left">{{ number_format($item->paid_amountuantity ?? 0,2) }}</td>
    
                                <td style="font-size: 12px;text-align: left">{{ number_format($item->grand_total,2) }}</td>
    
                            </tr>
                        @endforeach

                        @php
                            $owe = $total - $paid;
                        @endphp

                    <tr>
                        <td colspan="5"></td>
                        <td>Total Owings:</td>
                        <td class="text-center">{{ number_format($owe,2) }}</td>
                  </tr>
				</tbody>
			</table>
            <div class="text-center" style="margin:30px 0 50px;">
            <small>Generated By {{ $company?->name ?? "" }}</strong></small>
        </div>
		</div>
	</div>
</div>

<script type="text/javascript">
    function auto_print() {     
        window.print()
    }
    setTimeout(auto_print, 1000);
</script>

</body>
</html>